enum KoreanRegion {
	SEOUL = '서울특별시',
	BUSAN = '부산광역시',
	DAEGU = '대구광역시',
	INCHEON = '인천광역시',
	GWANGJU = '광주광역시',
	DAEJEON = '대전광역시',
	ULSAN = '울산광역시',
	SEJONG = '세종특별자치시',
	GYEONGGI = '경기도',
	GANGWON = '강원도',
	CHUNGBUK = '충청북도',
	CHUNGNAM = '충청남도',
	JEONBUK = '전라북도',
	JEONNAM = '전라남도',
	GYEONGBUK = '경상북도',
	GYEONGNAM = '경상남도',
	JEJU = '제주특별자치도',
}
enum SeoulDistrict {
	JONGNO = '종로구',
	JUNG = '중구',
	YONGSAN = '용산구',
	SEONGDONG = '성동구',
	GWANGJIN = '광진구',
	DONGDAEMUN = '동대문구',
	JUNGNANG = '중랑구',
	SUNGDONG = '성북구',
	GANGBUK = '강북구',
	DOBONG = '도봉구',
	NOWON = '노원구',
	EUNPYEONG = '은평구',
	SEODAEMUN = '서대문구',
	MAPO = '마포구',
	YANGCHEON = '양천구',
	GANGSEO = '강서구',
	GURO = '구로구',
	GEUMCHEON = '금천구',
	YEONGDEUNGPO = '영등포구',
	DONGJAK = '동작구',
	GWANAK = '관악구',
	SEOCHO = '서초구',
	GANGNAM = '강남구',
	SONGPA = '송파구',
	GANGDONG = '강동구',
}
enum BusanDistrict {
	JUNG_GU = '중구',
	SEO_GU = '서구',
	DONG_GU = '동구',
	YEONJE_GU = '연제구',
	NAM_GU = '남구',
	BUK_GU = '북구',
	HAEUNDAE_GU = '해운대구',
	SASEO_GU = '사상구',
	GEUMJEONG_GU = '금정구',
	GANGSEO_GU = '강서구',
	YEOENGDO_GU = '영도구',
	SASANG_GU = '사상구',
	GYEOENGJUNG_GU = '기장군',
}
enum DaeguDistrict {
	JUNG_GU = '중구',
	DONG_GU = '동구',
	SEO_GU = '서구',
	NAM_GU = '남구',
	BUK_GU = '북구',
	SU_GU = '수성구',
	DALSEO_GU = '달서구',
	DALSEONG = '달성군',
}
enum IncheonDistrict {
	JUNG_GU = '중구',
	NAM_GU = '남구',
	DONG_GU = '동구',
	YEONSU_GU = '연수구',
	NAM_DONG_GU = '남동구',
	BUPYEONG_GU = '부평구',
	GYEOSON_GU = '계양구',
	SEOGU_GU = '서구',
	GANGHWAGU_GU = '강화군',
	ONGJINGU_GU = '옹진군',
}
enum GwangjuDistrict {
	JUNG_GU = '중구',
	DONG_GU = '동구',
	SEO_GU = '서구',
	NAM_GU = '남구',
	BUK_GU = '북구',
	GWANGSAN_GU = '광산구',
}
enum DaejeonDistrict {
	JUNG_GU = '중구',
	DONG_GU = '동구',
	SEO_GU = '서구',
	YUSEONG_GU = '유성구',
	DAEDU_GU = '대덕구',
}
enum UlsanDistrict {
	JUNG_GU = '중구',
	NAM_GU = '남구',
	DONG_GU = '동구',
	BUK_GU = '북구',
	ULJIN = '울진군',
}
enum SejongDistrict {
	SEOCHANG = '세종특별자치시'
}

enum GyeonggiDistrict {
	SUWON = '수원시',
	SUWON_YONGTONG = '수원시 영통구',
	SUWON_JANGAN = '수원시 장안구',
	SUWON_SUJEONG = '수원시 수정구',
	SUWON_HYANGNOWON = '수원시 권선구',
	SUWON_PALDAL = '수원시 팔달구',
	SEOUL = '성남시',
	SEOUL_BUNDANG = '성남시 분당구',
	SEOUL_SONGPA = '성남시 수정구',
	SEOUL_SUJEONG = '성남시 중원구',
	INCHEON = '의정부시',
	INCHEON_BUPYEONG = '의정부시 미추홀구',
	INCHEON_GYESAN = '의정부시 계양구',
	INCHEON_SEOKSU = '의정부시 남구',
	GOYANG = '안양시',
	GOYANG_DONGAN = '안양시 동안구',
	GOYANG_ILLWON = '안양시 만안구',
	HWASEONG = '부천시',
	PYEONGTAEK = '광명시',
	ANSAN = '평택시',
	ANSAN_DANWON = '안산시 단원구',
	ANSAN_SANGNOK = '안산시 상록구',
	YONGIN = '화성시',
	YONGIN_SUJI = '용인시 수지구',
	YONGIN_SUWON = '용인시 수원구',
	YONGIN_SONGDAM = '용인시 동안구',
	YONGIN_CHEONGSA = '용인시 청안구',
	YONGIN_JUNGWON = '용인시 분당구',
	YONGIN_GIHEUNG = '용인시 이천구',
	YONGIN_GWANGJU = '용인시 팔달구',
	YONGIN_YONGIN = '용인시 원미구',
	OSAN = '군포시',
	SIHEUNG = '시흥시',
	GUNPO = '김포시',
	ANYANG = '남양주시',
	SUWON_SANGNOK = '광주시',
	SUWON_SINJEONG = '포천시',
	SUWON_SINJANG = '여주시',
	SUWON_DONGJIN = '양평군',
	SUWON_PALDALGO = '동두천시',
	SUWON_GWANGJEONG = '안성시',
	SUWON_MANAN = '오산시',
	SUWON_SUNGNAM = '화성시',
}
export {KoreanRegion}